accounts/urls.py
from django.urls import path # type: ignore
from . import views

app_name="accounts"

urlpatterns = [
   path('', views.loginaccount, name='loginaccount'),
   path('logout/', views.logoutaccount, name='logoutaccount'),
   path("password-reset/", views.request_password_reset, name="request_password_reset"),
   path("verify-otp/", views.verify_otp, name="verify_otp"),
   path("reset-password/", views.reset_password, name="reset_password"),
]

adminside/urls.py
from django.urls import path # type: ignore
from . import views

app_name = "adminside"

urlpatterns = [
    path('', views.home, name='home'),  
    path('dashboard/', views.dashboard, name='dashboard'),
    path('branches/', views.branches, name='branches'),
    path('suppliers/', views.suppliers, name='suppliers'),
    path('purchase/', views.purchase, name='purchase'),
    path('categories/', views.categories, name='categories'),
    path('inventory/', views.inventory, name='inventory'),
    path('fooditems/', views.fooditems, name='fooditems'),
    path('tables/', views.tables, name='tables'),
    path('customer/', views.customer, name='customer'),
    path('staff/', views.staff, name='staff'),
    path('sales/', views.sales, name='sales'),
    path('reports/', views.reports, name='reports'),
    path('settings/', views.adminside_settings_view, name='settings'),
    path('profile/', views.profile, name='profile'),
    path("update-profile-pic/", views.update_profile_pic, name="update_profile_pic"),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),
]

pos/urls.py
from django.contrib import admin # type: ignore
from django.urls import path,include # type: ignore
from django.conf import settings # type: ignore
from django.conf.urls.static import static # type: ignore

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include(("accounts.urls", "accounts"), namespace="accounts")),
    path("adminside/", include(("adminside.urls", "adminside"), namespace="adminside")),
    path("staffside/", include(("staffside.urls", "staffside"), namespace="staffside")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminside/views.py
from collections import defaultdict
from django.shortcuts import render, redirect, get_object_or_404  # type: ignore
from .forms import CustomPasswordChangeForm
from django.db import connection # type: ignore
from .models import Staff,Branch,Supplier,Purchase,Categories,Inventory,FoodItem,Table,Customer,Sales_reports
from .forms import StaffForm,BranchForm,SupplierForm,PurchaseForm,CategoryForm,InventoryForm,CustomerForm
from django.contrib import messages # type: ignore
from django.utils import timezone # type: ignore
from django.contrib.auth.decorators import login_required # type: ignore
from django.contrib.auth import update_session_auth_hash # type: ignore
from django.contrib.messages import get_messages # type: ignore
from django.contrib.messages.storage.fallback import FallbackStorage # type: ignore
from staffside.models import Sales,Notification,NotificationSeen,Order
from django.utils.timezone import now # type: ignore
from datetime import datetime
from datetime import date
from django.conf import settings # type: ignore
from django.utils import timezone # type: ignore
from collections import defaultdict
from django.db.models import Sum, Count # type: ignore
from datetime import datetime, timedelta
import random
from django.db.models.functions import TruncMonth # type: ignore
import re
import csv
from django.http import JsonResponse # type: ignore
from datetime import date
from django.db.models import F, Sum # type: ignore



def render_page(request, template, data=None):
    today = timezone.now().date()

    context = {
        "template": template,
        "user": request.user,
        "login_date": request.session.get("login_date"),
        "open_notifications": request.GET.get("open_notifications") == "true"
    }

    if request.user.is_authenticated:
        all_notifications = Notification.objects.filter(created_at__date=today).order_by("-created_at")

        unseen_notifications = all_notifications.exclude(
            notificationseen__user=request.user,
            notificationseen__seen=True
        )

        context["notifications"] = all_notifications
        context["has_unseen"] = unseen_notifications.exists()
        context["unseen_notifications"] = unseen_notifications 

        if "mark_seen" in request.GET:
            NotificationSeen.objects.bulk_create([
                NotificationSeen(user=request.user, notification=n, seen=True)
                for n in unseen_notifications
            ], ignore_conflicts=True)

    else:
        context["notifications"] = []
        context["has_unseen"] = False

    if data:
        context.update(data)

    return render(request, "adminside/base.html", context)

# Home View
def home(request):
    messages.success(request, "✅ Login successful!")  
    return redirect("adminside:dashboard")

# Dashboard View
def dashboard(request):
    total_orders = Order.objects.count()

    best_employee = (
        Order.objects.values("staff__staff_fullname", "staff__branch__location")
        .annotate(order_count=Count("order_id"))
        .order_by("-order_count")
        .first()
    )

    if best_employee:
        best_employee_name = best_employee["staff__staff_fullname"]
        best_employee_branch = best_employee["staff__branch__location"]
    else:
        best_employee_name = "N/A"
        best_employee_branch = "N/A"


    total_sales = Sales.objects.aggregate(total=Sum('order__final_total'))['total'] or 0

    total_cost = Purchase.objects.aggregate(total_cost=Sum(F('cost_price') * F('quantity')))['total_cost'] or 0
    total_profit = total_sales - total_cost


    
    last_week = datetime.today() - timedelta(days=7)
    weekly_sales = (
        Sales.objects.filter(date__gte=last_week)
        .aggregate(total=Sum('order__final_total'))['total'] or 0
    )

    today = datetime.today()
    last_week = today - timedelta(days=7)
    sales_data = (
        Sales.objects
        .filter(date__gte=last_week) 
        .values('date')
        .annotate(total=Sum('order__final_total'))
        .order_by('date')
    )

    sales_labels = [data['date'].strftime('%Y-%m-%d') for data in sales_data]
    sales_values = [data['total'] for data in sales_data]

    best_selling_items = Order.objects.values_list('ordered_items', flat=True)
    item_count = defaultdict(lambda: {"quantity": 0, "total_price": 0, "image": "", "price": 0})

    for items in best_selling_items:
        for item_name, details in items.items():
            base_name = item_name.split('_')[0]  

            if base_name in item_count:
                item_count[base_name]["quantity"] += details["quantity"]
                item_count[base_name]["total_price"] += details["quantity"] * details["price"]
            else:
                item_instance = Inventory.objects.filter(purchase__food_item__icontains=base_name).first()

                item_count[base_name] = {
                    "quantity": details["quantity"],
                    "total_price": details["quantity"] * details["price"],
                    "image": item_instance.image.url if item_instance and item_instance.image else "/static/images/default.png",
                    "price": details["price"],
                }

    sorted_items = sorted(item_count.items(), key=lambda x: x[1]["quantity"], reverse=True)[:5]

    top_items = [
        {"name": item[0], "quantity": item[1]["quantity"], "total_price": item[1]["total_price"], "image": item[1]["image"], "price": item[1]["price"]}
        for item in sorted_items
    ]

    monthly_profit_data = (
        Sales.objects.annotate(month=TruncMonth('date'))  
        .values('month')
        .annotate(revenue=Sum('order__final_total'))
        .order_by('month')
    )

    monthly_cost_data = (
        Purchase.objects.annotate(month=TruncMonth('purchased_date'))
        .values('month')
        .annotate(cost=Sum('cost_price'))
        .order_by('month')
    )

    cost_dict = {data['month']: data['cost'] for data in monthly_cost_data}

    profit_trend_labels = [data['month'].strftime('%Y-%m') for data in monthly_profit_data]
    profit_trend_labels = [datetime.strptime(label, "%Y-%m").strftime("%B") for label in profit_trend_labels]
    profit_trend_values = [data['revenue'] - cost_dict.get(data['month'], 0) for data in monthly_profit_data]

    all_categories = list(Categories.objects.values_list('categories_name', flat=True))

    category_totals = {category: 0 for category in all_categories}

    category_sales = Sales.objects.filter(order__ordered_items__isnull=False).values('order__ordered_items')

    for sale in category_sales:
        ordered_items = sale["order__ordered_items"]
        
        for item_name, details in ordered_items.items():
            base_name = "_".join(item_name.split("_")[:-1]) if "_" in item_name else item_name

            item_instance = Inventory.objects.filter(purchase__food_item__icontains=base_name).first()
            category_name = item_instance.category.categories_name if item_instance and item_instance.category else None

            if category_name in category_totals:
                category_totals[category_name] += details["quantity"] * details["price"]

    category_labels = list(category_totals.keys())
    category_values = list(category_totals.values())
    def generate_colors(n):
         return [f"#{random.randint(0, 0xFFFFFF):06x}" for _ in range(n)]

    category_colors = generate_colors(len(category_labels))


    def generate_bar_colors(n):
        color_palette = ["#F9C784", "#F8B400", "#FF5733", "#36A2EB", "#4BC0C0", 
                        "#9966FF", "#FF6384", "#2ECC71", "#D35400", "#1F618D"]
        return [random.choice(color_palette) for _ in range(n)]

    bar_colors = generate_bar_colors(len(profit_trend_values))


    context = {
        'total_orders': total_orders,
        'total_sales': total_sales,
        'best_employee_name': best_employee_name,
        'best_employee_branch': best_employee_branch,
        'sales_labels': sales_labels,
        'sales_values': sales_values,
        'weekly_sales': weekly_sales,
        'total_profit': total_profit,
        'total_revenue': total_sales,
        'total_cost': total_cost,
        'profit_margin': round((total_profit / total_sales) * 100, 2) if total_sales else 0,
        'profit_trend_labels': profit_trend_labels,
        'profit_trend_values': profit_trend_values,
        'top_items': top_items,
        'category_labels': category_labels,
        'category_values': category_values,
        "category_colors": category_colors,
        "bar_colors": bar_colors,
    }

    return render_page(request, 'adminside/dashboard.html', context)

# Staff View
def staff(request):
    branches = Branch.objects.all()
    staff_members = Staff.objects.all()

    if request.method == 'POST':
        if 'delete_staff_id' in request.POST:
            staff_id = request.POST.get('delete_staff_id')
            staff = get_object_or_404(Staff, staff_id=staff_id)
            staff.delete()
            messages.success(request, f'Staff member "{staff.username}" deleted successfully.')
            return redirect('adminside:staff')

        staff_id = request.POST.get('staff_id')

        form_data = request.POST.copy()  
        form_data['username'] = form_data.get('staff_username')  
        form_data['password'] = form_data.get('staff_password')  

        if staff_id:
            staff = Staff.objects.get(staff_id=staff_id)
            form = StaffForm(form_data, request.FILES, instance=staff)
            message = f'Staff "{staff.username}" updated successfully.'
        else:
            form = StaffForm(form_data, request.FILES)            
            message = 'New staff member added successfully.'


        if form.is_valid():
            staff = form.save(commit=False)
            staff.save()      
            messages.success(request, message)
            return redirect('adminside:staff')
        else:

adminside/templates/adminside/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  {% block title %}
  <title>POS System</title>
  {% endblock %}

  <!-- bootstrap CDN -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" />
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


  <!-- Font awesome CDN -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" />

  <!-- base.html css (style.css) -->
  {% block css%}
  <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  {% endblock %}

  <style>
    .notification-container {
      position: relative;
      display: inline-block;
      margin-top: 10px;
    }

    .notification-link {
      position: relative;
      font-size: 18px;
      color: black;
      text-decoration: none;
      cursor: pointer;
    }

    .notification-dot {
      width: 8px;
      height: 8px;
      background-color: #FF8C42;
      border-radius: 50%;
      position: absolute;
      top: 2px;
      right: 2px;
    }

    .notifications-dropdown {
      display: none;
      position: absolute;
      width: 280px;
      max-height: 250px;
      background: white;
      box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.2);
      padding: 10px;
      border-radius: 8px;
      right: 10px;
      top: 50px;
      z-index: 1000;
      overflow-y: auto;
      white-space: normal;
    }

    .notifications-dropdown h4 {
      margin: 0;
      padding-bottom: 10px;
      font-size: 16px;
      border-bottom: 1px solid #ddd;
    }

    .notifications-dropdown ul {
      padding: 0;
      list-style: none;
    }

    .notifications-dropdown ul li {
      padding: 8px;
      font-size: 14px;
      border-bottom: 1px solid #f0f0f0;
    }

    .notifications-dropdown ul li:last-child {
      border-bottom: none;
    }

    @media (max-width: 530px) {
      .notifications-dropdown {
        width: 90%;
        right: 5%;
        left: auto;
        max-height: 200px;
        top: 45px;
      }
    }

    /* Center and add horizontal scrolling on small screens */
    @media (max-width: 400px) {
      .notifications-dropdown {
        left: 50%;
        transform: translateX(-50%);
        width: 90%;
        max-width: 200px;
        /* Prevents it from being too wide */
        overflow-x: auto;
        /* Allow horizontal scrolling */
        white-space: nowrap;
        /* Prevents text wrapping */
      }
    }

    .profile-container {
      position: relative;
      display: inline-block;
    }

    .profile-dropdown {
      display: none;
      position: absolute;
      top: 70px;
      right: 0;
      background: white;
      box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.2);
      padding: 30px;
      border-radius: 8px;
      z-index: 1000;
      align-items: center;
      /* Center items horizontally */
      text-align: center;
      /* Center text */
    }

    .profile-dropdown img {
      width: 50px;
      /* Slightly larger for better visibility */
      height: 50px;
      border-radius: 50%;
      margin-bottom: 10px;
    }

    .profile-dropdown h5 {
      margin: 0;
      font-size: 16px;
    }

    .profile-dropdown p {
      font-size: 14px;
      color: gray;
    }

    .profile-dropdown a {
      display: block;
      padding: 8px;
      text-decoration: none;
      color: black;
      font-size: 14px;
      text-align: center;

    }

    .profile-dropdown a:hover {
      background-color: #f0f0f0;
      border-radius: 5px;
    }
  </style>
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200..1000;1,200..1000&display=swap"
    rel="stylesheet" />
</head>

<body>
  <div class="top-navbar">
    <div class="user-info">

      <div class="notification-container">
        <a href="#" class="notification-link" onclick="toggleNotifications(event)">
          <i class="fa-solid fa-bell"></i>
          {% if has_unseen %}
          <span id="notification-dot" class="notification-dot" style="background-color: orange;"></span>
          {% endif %}
        </a>

        <div id="notificationDropdown" class="notifications-dropdown"
          style="{% if open_notifications %}display: block;{% else %}display: none;{% endif %}">
          <h4>Notifications</h4>
          <ul>
            {% for notification in notifications %}
            <li style="{% if notification in unseen_notifications %}font-weight: bold;{% endif %}">
              {{ notification.message }}
            </li>
            {% empty %}
            <li>No new notifications</li>
            {% endfor %}
          </ul>
        </div>
      </div>

      <script>
        function toggleNotifications(event) {
          event.preventDefault(); // Prevent default link behavior

          let dropdown = document.getElementById("notificationDropdown");
          let dot = document.getElementById("notification-dot");

          if (dot) {
            dot.remove();
            let newUrl = window.location.href.includes("?") ? window.location.href + "&mark_seen=true" : "?mark_seen=true";
            history.replaceState(null, null, newUrl); // Update URL without reloading
          }
          dropdown.style.display = dropdown.style.display === "block" ? "none" : "block";
          dropdown.style.width = "250px"; // Ensures proper width


        }
        document.addEventListener("click", function (event) {
          let dropdown = document.getElementById("notificationDropdown");
          let bell = document.querySelector(".notification-link");

          if (!dropdown.contains(event.target) && !bell.contains(event.target)) {
            dropdown.style.display = "none";
          }
        });
      </script>


      <div class="profile-container">
        <img src="{{ user.staff_img.url }}?{{ user.staff_img }}" alt="Profile Image"
          class="staff-profile-img rounded-circle" id="profileImage"
          style="width: 50px; height: 50px; object-fit: cover; cursor: pointer;border:1px solid black;">

        <!-- Dropdown Menu -->
        <div id="profileDropdown" class="profile-dropdown">
          <img src="{{ user.staff_img.url }}?{{ user.staff_img }}" alt="Profile Image"
            class="staff-profile-img rounded-circle" id="profileImage"
            style="width: 50px; height: 50px; object-fit: cover; cursor: pointer;border: 1px solid black;">
          <h5>{{ user.username }}</h5>
          <p>{{ user.staff_email }}</p>
          <hr>
          <a href="{% url 'adminside:settings' %}"><i class="fa fa-cogs"></i> Settings</a>
          <a href="{% url 'accounts:logoutaccount' %}"><i class="fa fa-sign-out"></i> Logout</a>
        </div>
      </div>
    </div>
  </div>

  <script>
    document.addEventListener("DOMContentLoaded", function () {
      let profileImage = document.getElementById("profileImage");
      let profileDropdown = document.getElementById("profileDropdown");

      profileImage.addEventListener("click", function (event) {
        event.stopPropagation(); // Prevent event bubbling
        profileDropdown.style.display = (profileDropdown.style.display === "block") ? "none" : "block";
      });

      // Close dropdown when clicking outside
      document.addEventListener("click", function (event) {
        if (!profileDropdown.contains(event.target) && event.target !== profileImage) {
          profileDropdown.style.display = "none";
        }
      });
    });
  </script>

  <div class="sidebar" id="sidebar">
    <div class="pos-name">
      <h2>POS System</h2>
    </div>
    <ul>
      <li>
        <a href="{% url 'adminside:dashboard' %}"
          class="nav-link {% if request.path == '/adminside/dashboard/' %}active{% endif %}">
          <i class="fa fa-home"></i><span> Dashboard</span></a>
      </li>
      <li>
        <a href="{% url 'adminside:branches' %}"
          class="nav-link {% if request.path == '/adminside/branches/' %}active{% endif %}">
          <i class="fas fa-city"></i><span> Branches</span></a>
      </li>
      <li>
        <a href="{% url 'adminside:suppliers' %}"
          class="nav-link {% if request.path == '/adminside/suppliers/' %}active{% endif %}">
          <i class="fa fa-truck"></i><span> Suppliers</span></a>
      </li>
      <li>
        <a href="{% url 'adminside:categories' %}"
          class="nav-link {% if request.path == '/adminside/categories/' %}active{% endif %}">
          <i class="fa-solid fa-layer-group"></i><span> Categories</span></a>
      </li>
      <li>
        <a href="{% url 'adminside:purchase' %}"
          class="nav-link {% if request.path == '/adminside/purchase/' %}active{% endif %}">
          <i class="fa fa-credit-card"></i><span> Purchase</span></a>
      </li>
      <li>
        <a href="{% url 'adminside:inventory' %}"
          class="nav-link {% if request.path == '/adminside/inventory/' %}active{% endif %}">
          <i class="fa fa-archive"></i><span> Inventory</span></a>
      </li>
      <li>
        <a href="{% url 'adminside:fooditems' %}"
          class="nav-link {% if request.path == '/adminside/fooditems/' %}active{% endif %}">
          <i class="fa fa-cutlery"></i><span> Food Items</span></a>
      </li>
      <li>
        <a href="{% url 'adminside:tables' %}"
          class="nav-link {% if request.path == '/adminside/tables/' %}active{% endif %}">
          <i class="fa-solid fa-table"></i><span> Tables</span></a>
      </li>
      <li>
        <a href="{% url 'adminside:customer' %}"
          class="nav-link {% if request.path == '/adminside/customer/' %}active{% endif %}">
          <i class="fa fa-user"></i><span> Customer</span></a>
      </li>
      <li>
        <a href="{% url 'adminside:staff' %}"
          class="nav-link {% if request.path == '/adminside/staff/' %}active{% endif %}">
          <i class="fa fa-users"></i><span> Staff</span></a>
      </li>
      <li>
        <a href="{% url 'adminside:sales' %}"
          class="nav-link {% if request.path == '/adminside/sales/' %}active{% endif %}">
          <i class="fa-solid fa-receipt"></i><span>Sales</span></a>
      </li>
      <li>
        <a href="{% url 'adminside:reports' %}"
          class="nav-link {% if request.path == '/adminside/reports/' %}active{% endif %}">
          <i class="fa fa-file-alt"></i><span>Reports</span></a>
      </li>
      <li>
        <a href="{% url 'adminside:settings' %}"
          class="nav-link {% if request.path == '/adminside/settings/' %}active{% endif %}">
          <i class="fa fa-cogs"></i><span> Settings</span></a>
      </li>
      <li>
        <a href="{% url 'accounts:logoutaccount' %}">
          <i class="fa fa-sign-out"></i><span> Logout</span></a>
      </li>
    </ul>
  </div>

  <div class="content" id="content-area">{% include template %}</div>
</body>

</html>

adminside/templates/adminside/fooditems.html
{% load static %}
{% block title %}
<title>Food-Items</title>
{% endblock %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/fooditem_style.css' %}">
{% endblock %}

<div class="food-items-page">
  <div class="food-item-title mt-4">
    <h3>FOOD ITEMS</h3>

    
    <div class="search-container">
      <input type="text" id="searchInput" class="search-input" placeholder="Search by category or name">
      <button class="search-btn" onclick="toggleSearch()">
        <i class="fa fa-search"></i>
      </button>
    </div>
  </div>

  <div class="table-responsive">
    <table class="table fooditem-detail-table">
      <thead>
        <tr>
          <th>ID</th>
          <th>Image</th>
          <th>Name</th>
          <th>Category</th>
          <th>Description</th>
          <th>Price</th>
          <th>Quantity</th>
          <th>Branch</th>
          <th>Special</th>
        </tr>
      </thead>
      <tbody id="foodTableBody">
        {% for item in food_items %}
        <tr>
          <td>{{ item.id }}</td>
          <td>
            {% if item.image %}
            <img src="{{ item.image.url }}" alt="{{ item.name }}" width="50" height="50">
            {% else %}
            No Image
            {% endif %}
          </td>
          <td>{{ item.name }}</td>
          <td>{{ item.category.categories_name }}</td>
          <td>{{ item.description }}</td>
          <td>{{ item.price }}</td>
          <td>{{ item.quantity }}</td>
          <td>{{ item.branch.location }}</td>
          <td>
            {% if item.is_special %}
              <i class="fas fa-star" style="color: gold;"></i>
            {% else %}
              <i class="fas fa-circle" style="color: gray;"></i> 
            {% endif %}
          </td>
        </tr>
        {% empty %}
        <tr>
          <td colspan="9" style="text-align: center;">No food items available</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<script src="{% static 'js/fooditem_scripts.js' %}"></script>

adminside/templates/adminside/settings.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block title %}
    <title>Settings</title>
    {% endblock %}

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
    />

    {% block css %}
    <link rel="stylesheet" href="{% static 'css/settings_style.css' %}" />
    {% endblock %}

    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200..1000;1,200..1000&display=swap"
      rel="stylesheet"
    />
  </head>
  <body>
    <div class="top-navbar">
      <div class="user-info">
        <img src="{{ user.staff_img.url }}?{{ user.staff_img }}" alt="Profile Image" 
        class="staff-profile-img rounded-circle" 
        style="width: 50px; height: 50px; object-fit: cover;margin-left: -3px;margin-bottom: 8px;border: 1px solid black">
         </div>
    </div>

    <div class="sidebar" id="sidebar">
      <div class="pos-name">
        <h2>POS System</h2>
      </div>
      <ul>
        <li>
          <a
            href="{% url 'adminside:profile' %}"
            class="nav-link {% if request.path == '/adminside/profile/' %}active{% endif %}"
          >
            <i
              class="fa {% if request.path == '/profile/' %}fa-user-circle{% else %}fa-user{% endif %}"
            ></i>
            <span> Profile</span>
          </a>
        </li>
        <li>
          <a
            href="{% url 'adminside:edit_profile' %}"
            class="nav-link {% if request.path == '/adminside/edit_profile/' %}active{% endif %}"
          >
            <i
              class="fa {% if request.path == '/edit_profile/' %}fa-pen-to-square{% else %}fa-edit{% endif %}"
            ></i>
            <span> Edit Profile</span>
          </a>
        </li>
        <li>
          <a
            href="{% url 'adminside:change_password' %}"
            class="nav-link {% if request.path == '/adminside/change_password/' %}active{% endif %}"
          >
            <i
              class="fa {% if request.path == '/change_password/' %}fa-lock-open{% else %}fa-lock{% endif %}"
            ></i>
            <span> Change Password</span>
          </a>
        </li>
        <li>
          <a
            href="{% url 'adminside:dashboard' %}"
            class="nav-link {% if request.path == '/adminside/dashboard/' %}active{% endif %}"
          >
            <i
              class="fa {% if request.path == '/dashboard/' %}fa-tachometer-alt{% else %}fa-home{% endif %}"
            ></i>
            <span> Back to Dashboard</span>
          </a>
        </li>
      </ul>
    </div>

    <div class="content" id="content-area">{% include template %}</div>
  </body>
</html>